*** Variables ***
${TITLE_DATA}    TO DO LIST
${ADD_ITEM_DATA}    ADD ITEM
${TO-DO_TASKS_DATA}     TO-DO TASKS
${COMPLETED_DATA}   COMPLETED
${INPUT_TEXT1}   TEST_1
${INPUT_TEXT2}   TEST_2
${INPUT_TEXT3}   TEST_3
${INPUT_TEXT4}   TEST_4
${NULL_TEXT}    